### ISSUE TITLE
Got IndexError on editting a file outside of the current project

### ISSUE THREAD

**Issue by tk0miya** [soutaro/steep#854]
I got IndexError from Steep on editting a file outside of the current project (ex. source code of rubygems).
This is a stacktrace:

```
[Steep 1.5.0.pre.5] [interaction:interaction] [frontend] Received message from master: textDocument/completion(6CNjMYD5aQ)
[Steep 1.5.0.pre.5] [interaction:interaction] [background] [#handle_job] [#response_to_completion] path: ../../../../.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/hover_provider/ruby.rb, line: 114, column: 11, trigger: 
[Steep 1.5.0.pre.5] [interaction:interaction] [background] [#handle_job] [#response_to_completion] [completion_provider#run(line: 114, column: 11)] parsing took 0.000838 seconds
[Steep 1.5.0.pre.5] [interaction:interaction] [background] [#handle_job] [#response_to_completion] [completion_provider#run(line: 114, column: 11)] type_check! took 0.001397 seconds
[Steep 1.5.0.pre.5] [interaction:interaction] [background] [#handle_job] [#response_to_completion] Generating response took 0.00212 seconds
[Steep 1.5.0.pre.5] [interaction:interaction] [background] Unexpected error: #<IndexError: index 2 outside of array bounds: -2...2>
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/source/buffer.rb:274:in `fetch'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/source/buffer.rb:274:in `source_line'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/source.rb:370:in `block in find_nodes'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/source.rb:369:in `times'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/source.rb:369:in `each'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/source.rb:369:in `sum'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/source.rb:369:in `find_nodes'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/source.rb:423:in `without_unrelated_defs'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/completion_provider.rb:176:in `block in type_check!'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep.rb:180:in `measure'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/completion_provider.rb:173:in `type_check!'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/completion_provider.rb:201:in `block (2 levels) in run'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep.rb:180:in `measure'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/completion_provider.rb:200:in `block in run'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/completion_provider.rb:199:in `run'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/interaction_worker.rb:123:in `block (2 levels) in process_completion'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep.rb:180:in `measure'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/interaction_worker.rb:113:in `block in process_completion'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/interaction_worker.rb:112:in `process_completion'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/interaction_worker.rb:38:in `block in handle_job'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/interaction_worker.rb:24:in `handle_job'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.5] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/server/base_worker.rb:46:in `block in run'
```

**Comment by soutaro** [comment]
@tk0miya Is this fixed by #853?

**Comment by tk0miya** [comment]
No, #853 is not related to this bug. This is not fixed yet.

I don't find a way to fix this bug. It seems Steep does not have the source code of files outside the project.

```
[Steep 1.5.0.pre.6] [interaction:interaction] [frontend] Received message from master: textDocument/completion(EgP7SPK5RL)
[Steep 1.5.0.pre.6] [interaction:interaction] [background] [#handle_job] [#response_to_completion] path: ../../../../.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-be19744795c0/lib/steep/services/hover_provider/ruby.rb, line: 115, column: 11, trigger: 
[Steep 1.5.0.pre.6] [interaction:interaction] [background] [#handle_job] [#response_to_completion] [completion_provider#run(line: 115, column: 11)] parsing took 0.002139 seconds
[Steep 1.5.0.pre.6] [interaction:interaction] [background] [#handle_job] [#response_to_completion] [completion_provider#run(line: 115, column: 11)] type_check! took 0.002233 seconds
[Steep 1.5.0.pre.6] [interaction:interaction] [background] [#handle_job] [#response_to_completion] Generating response took 0.003364 seconds
[Steep 1.5.0.pre.6] [interaction:interaction] [background] Unexpected error: #<IndexError: index 2 outside of array bounds: -2...2>
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/source/buffer.rb:274:in `fetch'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/source/buffer.rb:274:in `source_line'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/source.rb:370:in `block in find_nodes'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/source.rb:369:in `times'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/source.rb:369:in `each'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/source.rb:369:in `sum'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/source.rb:369:in `find_nodes'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/source.rb:423:in `without_unrelated_defs'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/services/completion_provider.rb:179:in `block in type_check!'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep.rb:180:in `measure'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/services/completion_provider.rb:176:in `type_check!'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/services/completion_provider.rb:204:in `block (2 levels) in run'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep.rb:180:in `measure'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/services/completion_provider.rb:203:in `block in run'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/services/completion_provider.rb:202:in `run'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/interaction_worker.rb:123:in `block (2 levels) in process_completion'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep.rb:180:in `measure'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/interaction_worker.rb:113:in `block in process_completion'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/interaction_worker.rb:112:in `process_completion'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/interaction_worker.rb:38:in `block in handle_job'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/interaction_worker.rb:24:in `handle_job'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.0.pre.6] [interaction:interaction] [background]   /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/steep-7b6c9372fce1/lib/steep/server/base_worker.rb:46:in `block in run'
```

**Comment by soutaro** [comment]
Not sure if #872 fixes the issue...

**Comment by tk0miya** [comment]
I confirmed v1.5.0 works fine. I guess #872 fixed the crash :-)
